### ISSUE TITLE
Screen transition animations

### ISSUE THREAD

**Issue by iremlopsum** [andyboythekid/react-native-navigation-library#2]
Hey, saw your post on Reddit. First of all, lot's of love, this is awesome, and exactly the API I have been thinking about (especially regarding the modals). Your approach is awesome!

Just wondering, why wouldn't you use `useNativeDriver` on your animations? All of it is `transform` related anyways, isn't it?

**Comment by iremlopsum** [comment]
Aah, I fount that you actually are using it. My bad.

Another question though, I can't seem to get custom transitions to work. My code is the following

```javascriot
class App extends PureComponent {
  render() {
    const transitionConfig = {
      config: {
        timing: Animated.timing,
        duration: 10000,
        easing: Easing.bezier(.7, -0.98, .04, 1.62),
        useNativeDriver: true
      },
      animation: animatedValue => {
        return [
          {
            translateX: animatedValue.interpolate({
              inputRange: [-1, 0, 1],
              outputRange: [-150, 375, 0],
            }),
          },
        ]
      }
    }

    return (
      <View style={{ flex: 1, backgroundColor: 'purple' }}>
        <Navigator name='my-stack-navigator'>
          {({ navigation }) => {
            return (
              <View style={{ flex: 1 }}>
                <Stack>
                  <Home name="home" {...transitionConfig} />
                  <About name="about" {...transitionConfig} />
                </Stack>
              </View>
            )
          }}
        </Navigator>
      </View>
    );
  }
}

It doesn't crash or anything, but the animation just doesn't happen, transitions instantly. Any ideas?

**Comment by andyboythekid** [comment]
hey! thanks so much for taking a look - sorry i missed this, i guess i haven’t set up notifications. 

so it looks like the docs are wrong, i updated the animation api to let you generate any style property e.g opacity or something else, so you’ll need to return a style object from that function. so what you’re missing there is an outer property (‘transform’) returning your translations. let me know if that’s confusing lol i’m writing this on mobile

**Comment by iremlopsum** [comment]
Got it to work, pretty cool, and works great!

Just one thing. It seems like I don't really get `-1` in the interpolation of the `inputRange` which means I can not do animations on the previous screen (e.g. iOS like navigation animation where the prev screen in the stack moves a bit left)

Is that something that you plan working on? I think that's the only thing I miss at the moment, totally love the library otherwise 👍

**Comment by andyboythekid** [comment]
awesome, glad it's working. hmm are you referring to your animation there? could you perhaps update the input range to `[0, 0.5, 1]`? not sure if that would help. 

I could easily expose animation in and out props as well as the animated value ranges, I might just expose the entire transition component for custom animation screens? what do you think?

**Comment by iremlopsum** [comment]
In most situation I only care about exit, current, future states, so `[-1, 0, 1]`, where:

-1 defines the the state for the screen that is `stack.length - 1`,
0 defines active state
1 defines state on mount (? I guess the init screen state, before it's active).

I could potentially do this logic in `configOut` and define there that the screen should move `-width / 2` or something, but I've seen the guys at https://github.com/archriss/react-native-snap-carousel use this `[-1 , 0, 1]` method of doing it and absolutely loved using it. I've always missed the option to do it in navigation like this as well

**Comment by andyboythekid** [comment]
gotcha -- I think this will be super simple to setup, I've been working on a few other features but this will be on the list! I'll probably need to follow up with you again just to make sure I understand

**Comment by andyboythekid** [comment]
closed this -- i've migrated the lib. if its something you're still looking for / using, I can easily update that lib with the proposed API, as I've done something similar in this one now
